language: scala

sudo: false

scala:
  - 2.10.6
  - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION "library/compile" "examples/compile" clean "library/compile" "examples/compile"
  - sbt ++$TRAVIS_SCALA_VERSION compile clean compile clean compile clean compile
