language: scala

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  - wget http://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/0.9.0/protoc-gen-grpc-java-0.9.0-linux-x86_64.exe
  - mv protoc-gen-grpc-java-0.9.0-linux-x86_64.exe protoc-gen-grpc-java-0.9.0.exe
  - chmod +x protoc-gen-grpc-java-0.9.0.exe
  - sbt "compile" "test:compile"
