language: scala

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

scala:
  - 2.10.6
  - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION "grpc-scala/compile" "grpc-scala-examples/compile"
