language: scala

sudo: false

jdk:
  - oraclejdk8

script:
  - wget http://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/0.7.1/protoc-gen-grpc-java-0.7.1-linux-x86_64.exe
  - mv protoc-gen-grpc-java-0.7.1-linux-x86_64.exe protoc-gen-grpc-java-0.7.1.exe
  - chmod +x protoc-gen-grpc-java-0.7.1.exe
  - sbt "compile" "test:compile"
